/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.system.test;

import com.system.model.Purchase_model;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class Purchase extends javax.swing.JFrame {

    /**
     * Creates new form Purchase
     */
    public Purchase() {
        initComponents();
        jTextField1.requestFocus();
        jTextField5.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(18, 30, 49));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 99, 91, 34));

        jLabel1.setText("Item code");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 71, -1, 22));

        jLabel2.setText("Item Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 75, -1, -1));

        jTextField2.setEditable(false);
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 99, 97, 34));

        jTextField3.setEditable(false);
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 99, 87, 34));

        jLabel3.setText("QTY");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 75, -1, -1));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 99, 81, 34));

        jLabel4.setText("Price");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 75, -1, -1));

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item code", "Item Name", "Qty", "Total"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 151, 539, 178));

        jTextField5.setEditable(false);
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(782, 274, 100, 29));

        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(782, 321, 100, 31));

        jTextField7.setEditable(false);
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField7KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(782, 370, 100, 28));

        jLabel5.setText("Total Price");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 281, -1, -1));

        jLabel6.setText("Paid");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(744, 329, -1, -1));

        jLabel7.setText("Balance");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(727, 377, -1, -1));

        jTextField8.setEditable(false);
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField8KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 99, 82, 34));

        jLabel8.setText("unitPrice");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 75, 51, -1));

        jButton1.setText("Trash");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 361, 73, 37));

        jButton2.setText("Insert");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 361, -1, 37));

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 361, -1, 37));

        jButton4.setText("Clear Table");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 361, -1, 37));

        jButton5.setText("Test");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 237, 55, 36));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 106, 430, 360));

        jButton6.setText("Bill");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 460, 60, 30));

        jButton7.setText("Print");
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 460, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1380, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection(
                        "jdbc:mysql://localhost:3306/test", "root", "root");
                // System.out.println("connected");

                String query = "SELECT * FROM test.items WHERE item_code = ? ";
                PreparedStatement ps = con.prepareStatement(query);
                ps.setString(1, jTextField1.getText());

                ResultSet rs = ps.executeQuery();
                jTextField4.requestFocus();
                if (rs.next()) {
                    String name = rs.getString("item_name");
                    jTextField2.setText(name);

                    String buying_price = rs.getString("buying_price");
                    jTextField3.setText(buying_price);

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Item not availale check the item code and try again");
                    jTextField1.setText("");
                    jTextField1.requestFocus();
                }

            } catch (Exception ex) {
                System.out.println(ex.toString());
            }

        }
        if (evt.getKeyCode() == KeyEvent.VK_F1) {

            jTextField6.requestFocus();

        }


    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {

                double price = Double.parseDouble(jTextField3.getText());
                double qty = Double.parseDouble(jTextField4.getText());
                double total_price = Double.parseDouble(jTextField5.getText());
                if (qty == 0) {
                    JOptionPane.showMessageDialog(rootPane, "Quantity cant to be zero");
                    jTextField4.requestFocus();
                    jTextField4.setText("");
                } else {
                    double total = price * qty;
                    total_price = total + total_price;

                    jTextField8.setText(Double.toString(total));
                    jTextField5.setText(Double.toString(total_price));

                    jTextField8.requestFocus();
                }

            } catch (Exception ex) {
                System.out.println(ex.toString());
            }
        }


    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTextField8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyPressed

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            model.addRow(new Object[]{jTextField1.getText(), jTextField2.getText(), jTextField4.getText(), jTextField8.getText()});
            clearFields();
            jTextField1.requestFocus();
        }


    }//GEN-LAST:event_jTextField8KeyPressed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed

        try {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            }
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }

    }//GEN-LAST:event_jTable1KeyPressed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            double total = Double.parseDouble(jTextField5.getText());
            double paid = Double.parseDouble(jTextField6.getText());

            if (total > paid) {

                JOptionPane.showMessageDialog(rootPane, "Transaction failed");
                jTextField6.setText("");
                jTextField6.requestFocus();
            } else {

                double balance = paid - total;
                jTextField7.setText(Double.toString(balance));
                jTextField7.requestFocus();
            }
        }


    }//GEN-LAST:event_jTextField6KeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int selectedRow = jTable1.getSelectedRow();
            jTextField1.setText(model.getValueAt(selectedRow, 0).toString());
            jTextField2.setText(model.getValueAt(selectedRow, 1).toString());
            jTextField4.setText(model.getValueAt(selectedRow, 2).toString());
            jTextField8.setText(model.getValueAt(selectedRow, 3).toString());

            double unit = Double.parseDouble(jTextField8.getText());
            double qty = Double.parseDouble(jTextField4.getText());
            double price = unit / qty;
            jTextField3.setText(Double.toString(price));

        } catch (Exception ex) {
            System.out.println(ex.toString());

        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

            int selectedRowIndex = jTable1.getSelectedRow();
            model.removeRow(selectedRowIndex);

            double unit = Double.parseDouble(jTextField8.getText());
            double total = Double.parseDouble(jTextField5.getText());
            total = total - unit;
            jTextField5.setText(Double.toString(total));
            clearFields();

            // jTextField8.setText(model.getValueAt(selectedRow, 3).toString());
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int dbQty = 0;

        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/test", "root", "root");
            System.out.println("Connected");

            double grant = Double.parseDouble(jTextField5.getText());
            double paid = Double.parseDouble(jTextField6.getText());
            double balance = Double.parseDouble(jTextField7.getText());

            Date currentDate = new Date();
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            SimpleDateFormat timeformat = new SimpleDateFormat("hh:mm:ss a");
            String date = format.format(currentDate);
            Date parsed = format.parse(date);
            String time = timeformat.format(currentDate);
            java.sql.Date sqlDate = new java.sql.Date(parsed.getTime());

            String query4 = " INSERT INTO  `test`.`purchase_master` (`grant_total`,`paid`,`balance`,`bill_date`,`time`) VALUES (?,?,?,?,?)";
            PreparedStatement ps2 = con.prepareStatement(query4);

            ps2.setDouble(1, grant);
            ps2.setDouble(2, paid);
            ps2.setDouble(3, balance);
            ps2.setDate(4, sqlDate);
            ps2.setString(5, time);

            ps2.executeUpdate();

            Statement stm = con.createStatement();
            Statement stm1 = con.createStatement();
            Statement stm2 = con.createStatement();

            for (int i = 0; i < model.getRowCount(); i++) {

                int itemCode = Integer.parseInt(model.getValueAt(i, 0).toString());
                String name = model.getValueAt(i, 1).toString();
                int qty = Integer.parseInt(model.getValueAt(i, 2).toString());
                double unitPrice = Double.parseDouble(model.getValueAt(i, 3).toString());

                String query = "INSERT INTO `test`.`purchase` (`item_code`,`purchase_maseter_ref`,`item_name`,`Quantity`,`total`) VALUES ('" + itemCode + "',(select max(purchase_masterid) from purchase_master) ,'" + name + "','" + qty + "','" + unitPrice + "')";

                String sql = "Select * from test.stock where item_code_ref = ?";// check the item if available or not in the stock 
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setInt(1, itemCode);
                ResultSet rs = ps.executeQuery();

                if (rs.next()) {

                    dbQty = rs.getInt("quantity");
                    System.out.println("QTY : " + dbQty);
                    String query2 = "update test.stock set quantity = quantity + '" + qty + "' where item_code_ref ='" + itemCode + "'";
                    stm1.addBatch(query2);
                } else {

                    String query3 = "INSERT INTO `test`.`stock` (`item_code_ref`,`quantity`) VALUES ('" + itemCode + "', '" + qty + "')";
                    stm2.addBatch(query3);

                }

                stm.addBatch(query);
                //  String query2 = "update test.stock set quantity = quantity + '" + qty + "' where item_code_ref ='" + itemCode + "'";
                //  stm1.addBatch(query2);
                // System.out.println(query2);

            }

            int[] rowInserted = stm.executeBatch();
            int[] updated = stm1.executeBatch();
            int[] stockInsert = stm2.executeBatch();
            System.out.println("Rows inserted vetti");
            System.out.println("Total Rows : " + rowInserted.length);
            JOptionPane.showMessageDialog(rootPane, "Purchase added");
            jTable1.setModel(new DefaultTableModel(null, new String[]{"Item code", "Item Name", "Qty", "Total"}));

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(rootPane, ex);
            System.out.println("Kadum error" + ex.toString());
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        int i = jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        try {

            if (i >= 0) {

                double price = Double.parseDouble(jTextField3.getText());
                double qty = Double.parseDouble(jTextField4.getText());
                double unit = price * qty;
                jTextField8.setText(Double.toString(unit));

                model.setValueAt(jTextField1.getText(), i, 0);
                model.setValueAt(jTextField2.getText(), i, 1);
                model.setValueAt(jTextField4.getText(), i, 2);
                model.setValueAt(jTextField8.getText(), i, 3);

            }
            double total = 0;
            for (int a = 0; a < jTable1.getRowCount(); a++) {
                total = total + Double.parseDouble(jTable1.getValueAt(a, 3).toString());
            }
            jTextField5.setText(Double.toString(total));
            clearFields();
            jTextField1.requestFocus();

        } catch (Exception ex) {

            System.out.println(ex.toString());
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyPressed

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        try {
            int itemCode = 0;
            int qty = 0;
            String name = null;
            double unitPrice = 0.0;
            System.out.println("Item code           Name           QTY           price");
            for (int i = 0; i < model.getRowCount(); i++) {

                itemCode = Integer.parseInt(model.getValueAt(i, 0).toString());
                name = model.getValueAt(i, 1).toString();
                qty = Integer.parseInt(model.getValueAt(i, 2).toString());
                unitPrice = Double.parseDouble(model.getValueAt(i, 3).toString());

                System.out.println(itemCode + "                  " + name + "            " + qty + "            " + unitPrice);
                //System.out.println("item code : " + itemCode);
                //System.out.println("Name : " + name);
                //  System.out.println("QTY : " + qty);
                // System.out.println("Price : " + unitPrice);
            }
            double total = Double.parseDouble(jTextField5.getText());
            double Paid = Double.parseDouble(jTextField6.getText());
            double balance = Double.parseDouble(jTextField7.getText());
            // System.out.println("Item code           Name           QTY           price");
            // System.out.println(itemCode + "                  " + name + "            " + qty + "            " + unitPrice);
            System.out.println("Total : " + total);
            System.out.println("Paid : " + Paid);
            System.out.println("Balance : " + balance);
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }

    }//GEN-LAST:event_jTextField7KeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTable1.setModel(new DefaultTableModel(null, new String[]{"Item code", "Item Name", "Qty", "Total"}));
        jTextField5.setText("0");
        clearFields();
        jTextField1.requestFocus();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        try {
            ArrayList<Purchase_model> list = new ArrayList<>();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            Purchase_model pur = null;

            while (model.getRowCount() > 0) {

                pur = new Purchase_model();
                list.add(pur);

            }

        } catch (Exception ex) {

        }


    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        try {
            int itemCode = 0;
            int qty = 0;
            String name = null;
            double unitPrice = 0.0;
            double total = Double.parseDouble(jTextField5.getText());
            double Paid = Double.parseDouble(jTextField6.getText());
            double balance = Double.parseDouble(jTextField7.getText());
            System.out.println("Item code           Name           QTY           price");
            jTextArea1.append("");
            for (int i = 0; i < model.getRowCount(); i++) {

                itemCode = Integer.parseInt(model.getValueAt(i, 0).toString());
                name = model.getValueAt(i, 1).toString();
                qty = Integer.parseInt(model.getValueAt(i, 2).toString());
                unitPrice = Double.parseDouble(model.getValueAt(i, 3).toString());

                jTextArea1.append("\t\t Bill Records \n\n"
                        + "Referance number :\t\t\t " + name
                        + "\n=========================================================\n"
                        + "student name :\t\t\t " + qty + "\n\n"
                        + "student age :\t\t\t " + unitPrice + "\n\n"
                        + "student age :\t\t\t " + Paid + "\n\n"
                        + "student address :\t\t\t " + balance + "\n"
                        + "============================================================="
                );

                // System.out.println(itemCode + "                  " + name + "            " + qty + "            " + unitPrice);
                //System.out.println("item code : " + itemCode);
                //System.out.println("Name : " + name);
                //  System.out.println("QTY : " + qty);
                // System.out.println("Price : " + unitPrice);
            }
            // double total = Double.parseDouble(jTextField5.getText());
            //double Paid = Double.parseDouble(jTextField6.getText());
            //double balance = Double.parseDouble(jTextField7.getText());
            // System.out.println("Item code           Name           QTY           price");
            // System.out.println(itemCode + "                  " + name + "            " + qty + "            " + unitPrice);
            System.out.println("Total : " + total);
            System.out.println("Paid : " + Paid);
            System.out.println("Balance : " + balance);
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }

   /*     jTextArea1.append("\t\t Students records \n\n"
                + "Referance number :\t\t\t " + jTextField1.getText()
                + "\n=========================================================\n"
                + "student name :\t\t\t " + jTextField2.getText() + "\n\n"
                + "student age :\t\t\t " + jTextField3.getText() + "\n\n"
                + "student address :\t\t\t " + jTextField4.getText() + "\n"
                + "============================================================="
        );*/


    }//GEN-LAST:event_jButton6ActionPerformed
    private void clearFields() {

        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        //jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Purchase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
