/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.system.ui;

import com.system.DBConnection.Registration;
import com.system.DBOperations.Operations;
import com.system.test.Bill;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author PC
 */
public class SaleItem extends javax.swing.JFrame {

    PreparedStatement ps = null;
    ResultSet rs = null;

    public SaleItem() {
        initComponents();
        jTextField8.setText("0");
        
        
        
        
        
         JTableHeader Theader = jTable1.getTableHeader();
        Theader.setBackground(Color.MAGENTA);

        Theader.setForeground(Color.RED);
        jTable1.setRowHeight(30);
        Theader.setFont(new Font("Segoe UI", Font.BOLD, 20));
        jTable1.setFont(new Font("Segoe UI", Font.BOLD, 15));
        jTable1.setBackground(Color.white);

        ((DefaultTableCellRenderer) Theader.getDefaultRenderer()).setHorizontalAlignment(jLabel1.CENTER);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(jLabel1.CENTER);
        //  jTable1.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        jTable1.setDefaultRenderer(Object.class, centerRenderer);
        
        
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, 172, 34));

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 90, 172, 35));

        jTextField3.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 200, 94, 45));

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 200, 155, 45));

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 200, 129, 45));

        jTextField6.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jTextField6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField6FocusLost(evt);
            }
        });
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 200, 104, 45));

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField7KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 200, 133, 45));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Customer ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, -1, 34));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Customer Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 90, -1, 35));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("ITEM CODE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 168, -1, 21));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("ITEM NAME");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 168, -1, 21));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("ITEM PRICE");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 175, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("QTY");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 171, 41, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("UNIT PRICE");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 171, -1, -1));

        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 3, true));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Code", "Item Name", "Quantity", "Total"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 773, 268));

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(952, 396, 149, 40));

        jTextField9.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField9KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(952, 465, 149, 40));

        jTextField10.setEditable(false);
        jTextField10.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(952, 549, 149, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setText("Grand Total");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 400, -1, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setText("Paid");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 460, 60, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 51));
        jLabel10.setText("Balance");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 550, -1, 40));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\Icons\\Button-Add-icon.png")); // NOI18N
        jButton1.setText("INSERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, 140, -1));

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\icon java\\Refresh-icon (1).png")); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 600, 120, 60));

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 600, 150, 60));

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\Icons\\trash-icon (1).png")); // NOI18N
        jButton4.setText("TRASH");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 600, 150, 60));

        jButton5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 51, 51));
        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\icon java\\printer-icon.png")); // NOI18N
        jButton5.setText("Bill");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(917, 622, 110, 60));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\New folder (2)\\POS.PNG")); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -20, 580, 480));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\Icons\\POS3.png")); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, -1, 160));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\New folder (2)\\AP\\AP\\unnamed.png")); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, -50, 480, 430));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\Icons\\Close-icon.png")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, 40, 40));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\New folder (2)\\bill.PNG")); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 540, 260));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1160, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                Registration ob = new Registration();
                ob.db_connect();
                String query = "SELECT * FROM registration.customer_details where customer_id = ?";
                ps = ob.con.prepareStatement(query);
                ps.setString(1, jTextField1.getText());
                rs = ps.executeQuery();
                jTextField3.requestFocus();

                if (rs.next()) {
                    String name = rs.getString("first_name");
                    jTextField2.setText(name);

                } else {
                    JOptionPane.showMessageDialog(rootPane, "INVALID CUSTOMER ID");
                    jTextField1.setText("");
                    jTextField1.requestFocus();
                }

            } catch (Exception ex) {
                System.out.println(ex.toString());
            }

        }


    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            try {
                Registration ob = new Registration();
                ob.db_connect();
                String query = "SELECT * FROM registration.item_details where item_code = ?";
                ps = ob.con.prepareStatement(query);
                ps.setString(1, jTextField3.getText());
                rs = ps.executeQuery();
                jTextField6.requestFocus();
                if (rs.next()) {
                    String name = rs.getString("item_name");
                    jTextField4.setText(name);
                    String selling_price = rs.getString("selling_price");
                    jTextField5.setText(selling_price);

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Item not availale check the item code and try again");
                    jTextField3.setText("");
                    jTextField3.requestFocus();
                }

            } catch (Exception ex) {

                System.out.println(ex.toString());
            }

        }
        if (evt.getKeyCode() == KeyEvent.VK_F1) {

            jTextField9.requestFocus();

        }


    }//GEN-LAST:event_jTextField3KeyPressed

    private void jTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyPressed
        Operations ob = new Operations();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            int itemCode = Integer.parseInt(jTextField3.getText());
            int testQty = Integer.parseInt(jTextField6.getText());
            int dbQty = ob.checkqty(itemCode);
            System.out.println(dbQty);
            if (dbQty < testQty) {
                JOptionPane.showMessageDialog(rootPane, "OUT OF STOCK", "STOCK NOT AVAILABLE", JOptionPane.ERROR_MESSAGE);
                jTextField6.setText("");
                jTextField6.requestFocus();

            } else {

                try {

                    double buy_price = Double.parseDouble(jTextField5.getText());
                    double qty = Double.parseDouble(jTextField6.getText());
                    double total_price = Double.parseDouble(jTextField8.getText());

                    if (qty == 0) {
                        JOptionPane.showMessageDialog(rootPane, "QUANTITY CANT BE ZERO");
                        jTextField6.setText("");
                        jTextField6.requestFocus();
                    } else {

                        double total = buy_price * qty;
                        total_price = total + total_price;
                        jTextField8.setText(Double.toString(total_price));
                        jTextField7.setText(Double.toString(total));
                        jTextField7.requestFocus();
                    }
                } catch (Exception ex) {
                    System.out.println(ex);
                }
            }
        }


    }//GEN-LAST:event_jTextField6KeyPressed

    private void jTextField7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyPressed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            model.addRow(new Object[]{jTextField3.getText(), jTextField4.getText(), jTextField6.getText(), jTextField7.getText()});
            clearFields();
            jTextField3.requestFocus();

        }

    }//GEN-LAST:event_jTextField7KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        jTable1.setModel(new DefaultTableModel(null, new String[]{"Item Code", "Item Name", "Quantity", "Total"}));
        jTextField8.setText("0");
        clearFields();
        jTextField3.requestFocus();


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed


    }//GEN-LAST:event_jTable1KeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        try {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int selectedRow = jTable1.getSelectedRow();
            jTextField3.setText(model.getValueAt(selectedRow, 0).toString());
            jTextField4.setText(model.getValueAt(selectedRow, 1).toString());
            jTextField6.setText(model.getValueAt(selectedRow, 2).toString());
            jTextField7.setText(model.getValueAt(selectedRow, 3).toString());

            double unit = Double.parseDouble(jTextField7.getText());
            double qty = Double.parseDouble(jTextField6.getText());
            double price = unit / qty;
            jTextField5.setText(Double.toString(price));

        } catch (Exception ex) {
            System.out.println(ex.toString());

        }


    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        try {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

            int selectedRowIndex = jTable1.getSelectedRow();
            model.removeRow(selectedRowIndex);

            double unit = Double.parseDouble(jTextField7.getText());
            double total = Double.parseDouble(jTextField8.getText());
            total = total - unit;
            jTextField8.setText(Double.toString(total));
            clearFields();

        } catch (Exception ex) {
            System.out.println(ex.toString());
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        int i = jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        try {

            if (i >= 0) {

                double price = Double.parseDouble(jTextField5.getText());
                double qty = Double.parseDouble(jTextField6.getText());
                double unit = price * qty;
                jTextField7.setText(Double.toString(unit));

                model.setValueAt(jTextField3.getText(), i, 0);
                model.setValueAt(jTextField4.getText(), i, 1);
                model.setValueAt(jTextField6.getText(), i, 2);
                model.setValueAt(jTextField7.getText(), i, 3);

            }
            double total = 0;
            for (int a = 0; a < jTable1.getRowCount(); a++) {
                total = total + Double.parseDouble(jTable1.getValueAt(a, 3).toString());
            }
            jTextField8.setText(Double.toString(total));
            clearFields();
            jTextField9.setText("");
            jTextField10.setText("");
            jTextField3.requestFocus();

        } catch (Exception ex) {

            System.out.println(ex.toString());
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int dbQty = 0;
        int status = 0;
        try {
            Registration ob = new Registration();
            ob.db_connect();
            int customer_id = Integer.parseInt(jTextField1.getText());
            double grant = Double.parseDouble(jTextField8.getText());
            double paid = Double.parseDouble(jTextField9.getText());
            double balance = Double.parseDouble(jTextField10.getText());

            Date currentDate = new Date();
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            SimpleDateFormat timeformat = new SimpleDateFormat("hh:mm:ss a");
            String date = format.format(currentDate);
            Date parsed = format.parse(date);
            String time = timeformat.format(currentDate);
            java.sql.Date sqlDate = new java.sql.Date(parsed.getTime());

            String query = "INSERT INTO `registration`.`sale_master` (`customer_id_ref`,`grant_total`,`paid`,`balance`,`bill_date`,`bill_time`) VALUES (?,?,?,?,?,?)";
            ps = ob.con.prepareStatement(query);
            ps.setInt(1, customer_id);
            ps.setDouble(2, grant);
            ps.setDouble(3, paid);
            ps.setDouble(4, balance);
            ps.setDate(5, sqlDate);
            ps.setString(6, time);
            ps.executeUpdate();
            System.out.println("1");

            Statement stm = ob.con.createStatement();
            Statement stm1 = ob.con.createStatement();

            for (int i = 0; i < model.getRowCount(); i++) {

                int itemCode = Integer.parseInt(model.getValueAt(i, 0).toString());
                String name = model.getValueAt(i, 1).toString();
                int qty = Integer.parseInt(model.getValueAt(i, 2).toString());
                double unitPrice = Double.parseDouble(model.getValueAt(i, 3).toString());

                String query2 = "INSERT INTO `registration`.`sale_details` (`item_code_ref`,`sale_masterId_ref`,`item_name`,`quantity`,`total`) VALUES ('" + itemCode + "',(select max(sale_master_id) from sale_master),'" + name + "','" + qty + "','" + unitPrice + "')";

                String query3 = "SELECT * FROM registration.stock_details where item_code_ref = ?";
                PreparedStatement ps2 = ob.con.prepareStatement(query3);
                ps2.setInt(1, itemCode);
                rs = ps2.executeQuery();

                if (rs.next()) {
                    dbQty = rs.getInt("Quantity");
                    System.out.println("QTY : " + dbQty);

                    if (dbQty >= qty) {

                        String query4 = "update registration.stock_details set Quantity = Quantity - '" + qty + "' where item_code_ref = '" + itemCode + "'";
                        stm.addBatch(query4);
                        stm1.addBatch(query2);
                        status = 1;

                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Limited Stock is available" + " " + "ITEM CODE" + rs.getInt("item_code_ref") + "  " + dbQty + " is Available", "Check The stock", JOptionPane.ERROR_MESSAGE);

                    }

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Item code is not available");

                }

            }

            if (status == 1) {

                int[] rawInserted = stm1.executeBatch();
                int[] updatedStock = stm.executeBatch();
                System.out.println("vetti");
                System.out.println("Raw effected : " + rawInserted.length);
                JOptionPane.showMessageDialog(rootPane, "Sale record added & Transaction Success");

            } else {
                JOptionPane.showMessageDialog(rootPane, "Transaction Cancelled", "Due to unavailability of stock", JOptionPane.WARNING_MESSAGE);
            }

        } catch (Exception ex) {

            System.out.println(ex.toString());
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            double total_price = Double.parseDouble(jTextField8.getText());
            double paid = Double.parseDouble(jTextField9.getText());

            if (total_price > paid) {
                JOptionPane.showMessageDialog(rootPane, "AMOUNT IS TOO LESS");
                jTextField9.setText("");
                jTextField9.requestFocus();
            } else {

                double balance = paid - total_price;
                jTextField10.setText(Double.toString(balance));
            }
        }

    }//GEN-LAST:event_jTextField9KeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            Bill ob = new Bill();
            ob.setVisible(true);
            ob.pack();
            ob.setLocationRelativeTo(null);
            ob.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

            Date currentDate = new Date();
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            SimpleDateFormat timeformat = new SimpleDateFormat("hh:mm:ss a");
            String date = format.format(currentDate);
            Date parsed = format.parse(date);
            String time = timeformat.format(currentDate);

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            DefaultTableModel model2 = (DefaultTableModel) ob.jTable1.getModel();
            ob.jTextArea1.append(date + "\t\t\t" + time + "\n\n");
            ob.jTextArea1.append("NAME\t \tQTY\t \tTotal\n\n");

            for (int i = 0; i < model.getRowCount(); i++) {

                int itemCode = Integer.parseInt(model.getValueAt(i, 0).toString());
                String name = model.getValueAt(i, 1).toString();
                int qty = Integer.parseInt(model.getValueAt(i, 2).toString());
                double unitPrice = Double.parseDouble(model.getValueAt(i, 3).toString());

                model2.addRow(new Object[]{itemCode, name, qty, unitPrice});
                ob.jTextArea1.append(name + "\t \t" + qty + "\t\t" + unitPrice + "\n");

            }

            double price = Double.parseDouble(jTextField8.getText());
            double paid = Double.parseDouble(jTextField9.getText());
            double balacne = Double.parseDouble(jTextField10.getText());
            String msg = "THANK YOU COME AGAIN";
            ob.jTextArea1.append("\n");
            ob.jTextArea1.append("Total Amount\t" + price + "\nPaid\t" + paid + "\nBalance\t" + balacne + "\n\n\t" + msg);
        } catch (Exception ex) {

            System.out.println(ex.toString());
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField6FocusLost


    }//GEN-LAST:event_jTextField6FocusLost

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    public void clearFields() {
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaleItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaleItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaleItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaleItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaleItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

}
